### ISSUE TITLE
Нужен ли нам web.xml?

### ISSUE THREAD

**Issue by humb1t** [Sunagatov/OrderManagementSystem#1]
https://github.com/Sunagatov/OrderManagementSystem/blob/d7116369133867a78780dc75f805b88be9cfca3b/src/main/webapp/WEB-INF/web.xml#L1

**Comment by Sunagatov** [comment]
Пока в нём нет необходимости. Добавлю по надобности.

**Comment by humb1t** [comment]
https://github.com/Sunagatov/OrderManagementSystem/blob/feature/services/src/main/webapp/WEB-INF/web.xml
всё ещё есть

**Comment by Sunagatov** [comment]
Без него не компилиться проект почему то.

**Comment by Sunagatov** [comment]
Удалил web.xml. Все компилится теперь.  
Решение:
"For servlet container >=3, and NO web.xml web application, declares the following maven-war-plugin plugin, and set the failOnMissingWebXml option to false."
