### ISSUE TITLE
Objects#requireNonNull

### ISSUE THREAD

**Issue by humb1t** [Sunagatov/OrderManagementSystem#10]
https://github.com/Sunagatov/OrderManagementSystem/blob/fcca514335efdc726a51c3a554f5cd8f756b23e0/src/main/java/com/zufar/service/OrderService.java#L100

**Comment by humb1t** [comment]
Старая  ссылка недоступна, в новых ветках нет файла по этому пути

**Comment by Sunagatov** [comment]
Я удалил класс UtilService. И заменил метод UtilService.isObjectNull() на Objects.requireNonNull().

"Старая ссылка недоступна, в новых ветках нет файла по этому пути" - ты о чём?

**Comment by humb1t** [comment]
Принято
