### ISSUE TITLE
Code beauty

### ISSUE THREAD

**Issue by humb1t** [Sunagatov/OrderManagementSystem#11]
https://github.com/Sunagatov/OrderManagementSystem/blob/fcca514335efdc726a51c3a554f5cd8f756b23e0/src/main/java/com/zufar/service/OrderService.java#L104

Было бы красиво использовать конструктор или Builder вместо 
- set
- set
- set

**Comment by humb1t** [comment]
@Sunagatov сервис по старому пути недоступен

**Comment by Sunagatov** [comment]
Я сделал конструктор со всем атрибутами анотацией @AllArgsConstructor из Lombok.
Builder не имеет смысла, так все атрибуты у меня обязательные. А Builder как я понимаю предпочтительнее когда у класса переменное число атрибутов.

**Comment by humb1t** [comment]
Принято
