### ISSUE TITLE
Нужен ли слой сервисов в таком случае вообще?

### ISSUE THREAD

**Issue by humb1t** [Sunagatov/OrderManagementSystem#12]
https://github.com/Sunagatov/OrderManagementSystem/blob/7b0c4c8ac0fb8dd696a8fa9f04749d936c1eacc6/src/main/java/com/zufar/service/DaoService.java#L5

**Comment by humb1t** [comment]
Nevermind

**Comment by Sunagatov** [comment]
Не пойму вопроса. DaoService<T>  interface  - это абстракция над всеми моими сервисами. А все сервисы - это реализации данного интерфейса.
Для расширяемости я использую этот интерфейс везде, в моем случае во всех рест контроллерах
