### ISSUE TITLE
GET `/orders` without `/all`

### ISSUE THREAD

**Issue by humb1t** [Sunagatov/OrderManagementSystem#4]
https://github.com/Sunagatov/OrderManagementSystem/blob/fcca514335efdc726a51c3a554f5cd8f756b23e0/src/main/java/com/zufar/controller/OrderController.java#L24

По REST API не стоит добавлять `/all`

**Comment by Sunagatov** [comment]
Просто оставить слэш вместо /all?

**Comment by humb1t** [comment]
принято
