### ISSUE TITLE
Unsafe type casting

### ISSUE THREAD

**Issue by humb1t** [Sunagatov/OrderManagementSystem#5]
https://github.com/Sunagatov/OrderManagementSystem/blob/fcca514335efdc726a51c3a554f5cd8f756b23e0/src/main/java/com/zufar/controller/OrderController.java#L60

Стоит избегать подобных кастов

**Comment by humb1t** [comment]
https://github.com/Sunagatov/OrderManagementSystem/blob/7b0c4c8ac0fb8dd696a8fa9f04749d936c1eacc6/src/main/java/com/zufar/domain/order/OrderController.java#L59

Не совсем то, что я имел ввиду. 

Ты же на этапе компиляции знаешь что ты будешь работать только с OrderService - зачем проверки и cast если можно просто заинжектить нужную реализацию?

**Comment by Sunagatov** [comment]
Просто во всех рест контролерах я использую DaoService<T>, и в OrderController  я тоже использую DaoService<T> для единообразия, а не OrderService. 
DaoService<T> не имеет метода changeOrderStatus(), поэтому для этого единственного случая я делаю каст на OrderService.

**Comment by Sunagatov** [comment]
Я заменил DaoService на OrderService, чтобы не делать cast.
