### ISSUE TITLE
Entities naming

### ISSUE THREAD

**Issue by humb1t** [Sunagatov/OrderManagementSystem#7]
![image](https://user-images.githubusercontent.com/5635032/64621382-a24ece80-d3f6-11e9-8c19-1cc6e44ee8a8.png)
OrderItem, но Status - возможно стоит внести однообразие?

**Comment by Sunagatov** [comment]
Не понял тебя. Что ты имеешь ввиду? Вынести все в абстрактный класс?

**Comment by Sunagatov** [comment]
Я переименовал OrderItem на Item.

**Comment by humb1t** [comment]
принято
