### ISSUE TITLE
Дублирующие репозитории

### ISSUE THREAD

**Issue by humb1t** [Sunagatov/OrderManagementSystem#8]
https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/PagingAndSortingRepository.html является наследником https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html

**Comment by Sunagatov** [comment]
Теперь все мои репозиторияя расширяют интерфейс PagingAndSortingRepository.
CrudRepository я убрал.

**Comment by humb1t** [comment]
принято
