### ISSUE TITLE
Util классы зло

### ISSUE THREAD

**Issue by humb1t** [Sunagatov/OrderManagementSystem#9]
https://github.com/Sunagatov/OrderManagementSystem/blob/fcca514335efdc726a51c3a554f5cd8f756b23e0/src/main/java/com/zufar/service/UtilService.java#L5

**Comment by humb1t** [comment]
![image](https://user-images.githubusercontent.com/5635032/64950313-17edeb00-d88c-11e9-80bd-3742212e5dd2.png)

**Comment by Sunagatov** [comment]
UtilService  класс удалён.

**Comment by humb1t** [comment]
принято
